import { PropsWithChildren, ReactNode } from 'react';
import Footer from '../Footer';
import Navbar from '../Navbar';

import styles from './Layout.module.css';

function Head(props: { children: ReactNode }) {
  return null;
}

export default function Index({ children }: PropsWithChildren<{}>) {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Housecat - Affordable housing data explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
      <Footer />
    </div>
  );
}
