import React from 'react';
import { ConnectedViz, Viz } from '@wprdc-widgets/viz';
import { IndicatorWithData } from '@wprdc-types/profiles';
import { useGeography } from '@wprdc-connections/geo';

export default {
  title: 'Components/Viz',
  component: Viz,
};

export const Default = () => {
  const { geog } = useGeography('county-42003');
  if (!!geog) return <ConnectedViz indicatorSlug="pop-by-race" geog={geog} />;
  return null;
};

export const Other = () => {
  return <Viz indicator={INDICATOR} />;
};

const INDICATOR: IndicatorWithData = {
  id: 15,
  name: 'Population by Race',
  slug: 'pop-by-race',
  description: '',
  tags: [],
  childTags: [],
  context: [],
  timeAxis: {
    id: 2,
    name: 'Most recent census year and most recent ACS year',
    slug: 'most-recent-census-year-and-most-recent-acs-year',
    description: '',
    unit: 7,
    timeParts: [
      {
        slug: 'most-recent-census-year-and-most-recent-acs-year:2019',
        name: '2019',
        timePoint: '2019-01-01T00:00:00Z',
        timeUnit: '7',
      },
    ],
    dates: ['2019-01-01T00:00:00Z'],
    resourcetype: 'StaticTimeAxis',
  },
  variables: [
    {
      id: 188,
      name: 'Total',
      slug: 'pop-by-race-total',
      description: null,
      shortName: null,
      units: null,
      unitNotes: null,
      denominators: [],
      sources: [18],
      depth: 0,
      displayName: 'Total',
      percentLabel: '% of Total',
      numberFormatOptions: {},
      tags: [],
      context: [],
      childTags: [],
      resourcetype: 'CensusVariable',
    },
    {
      id: 189,
      name: 'White alone',
      slug: 'pop-by-race-white-alone',
      description: '',
      shortName: null,
      units: null,
      unitNotes: null,
      denominators: [
        {
          id: 188,
          name: 'Total',
          slug: 'pop-by-race-total',
          depth: 0,
          percentLabel: '% of Total',
          shortName: null,
          numberFormatOptions: {},
          tags: [],
          context: [],
        },
      ],
      sources: [18],
      depth: 1,
      displayName: 'White alone',
      percentLabel: '% of White alone',
      numberFormatOptions: {},
      tags: [],
      context: [],
      childTags: [],
      resourcetype: 'CensusVariable',
    },
    {
      id: 190,
      name: 'Black or African American alone',
      slug: 'pop-by-race-black-or-african-american-alone',
      description: '',
      shortName: 'Black alone',
      units: null,
      unitNotes: null,
      denominators: [
        {
          id: 188,
          name: 'Total',
          slug: 'pop-by-race-total',
          depth: 0,
          percentLabel: '% of Total',
          shortName: null,
          numberFormatOptions: {},
          tags: [],
          context: [],
        },
      ],
      sources: [18],
      depth: 1,
      displayName: 'Black or African American alone',
      percentLabel: '% of Black or African American alone',
      numberFormatOptions: {},
      tags: [],
      context: [],
      childTags: [],
      resourcetype: 'CensusVariable',
    },
    {
      id: 192,
      name: 'Asian alone',
      slug: 'pop-by-race-asian-alone',
      description: '',
      shortName: null,
      units: null,
      unitNotes: null,
      denominators: [
        {
          id: 188,
          name: 'Total',
          slug: 'pop-by-race-total',
          depth: 0,
          percentLabel: '% of Total',
          shortName: null,
          numberFormatOptions: {},
          tags: [],
          context: [],
        },
      ],
      sources: [18],
      depth: 1,
      displayName: 'Asian alone',
      percentLabel: '% of Asian alone',
      numberFormatOptions: {},
      tags: [],
      context: [],
      childTags: [],
      resourcetype: 'CensusVariable',
    },
    {
      id: 191,
      name: 'American Indian and Alaska Native alone',
      slug: 'pop-by-race-american-indian-and-alaska-native-alone',
      description: '',
      shortName: 'AIAN alone',
      units: null,
      unitNotes: null,
      denominators: [
        {
          id: 188,
          name: 'Total',
          slug: 'pop-by-race-total',
          depth: 0,
          percentLabel: '% of Total',
          shortName: null,
          numberFormatOptions: {},
          tags: [],
          context: [],
        },
      ],
      sources: [18],
      depth: 1,
      displayName: 'American Indian and Alaska Native alone',
      percentLabel: '% of American Indian and Alaska Native alone',
      numberFormatOptions: {},
      tags: [],
      context: [],
      childTags: [],
      resourcetype: 'CensusVariable',
    },
    {
      id: 193,
      name: 'Native Hawaiian and Other Pacific Islander alone',
      slug: 'pop-by-race-native-hawaiian-and-other-pacific-islander-alone',
      description: '',
      shortName: 'NHPI alone',
      units: null,
      unitNotes: null,
      denominators: [
        {
          id: 188,
          name: 'Total',
          slug: 'pop-by-race-total',
          depth: 0,
          percentLabel: '% of Total',
          shortName: null,
          numberFormatOptions: {},
          tags: [],
          context: [],
        },
      ],
      sources: [18],
      depth: 1,
      displayName: 'Native Hawaiian and Other Pacific Islander alone',
      percentLabel: '% of Native Hawaiian and Other Pacific Islander alone',
      numberFormatOptions: {},
      tags: [],
      context: [],
      childTags: [],
      resourcetype: 'CensusVariable',
    },
    {
      id: 194,
      name: 'Some other race alone',
      slug: 'pop-by-race-some-other-race-alone',
      description: '',
      shortName: 'Other race alone',
      units: null,
      unitNotes: null,
      denominators: [
        {
          id: 188,
          name: 'Total',
          slug: 'pop-by-race-total',
          depth: 0,
          percentLabel: '% of Total',
          shortName: null,
          numberFormatOptions: {},
          tags: [],
          context: [],
        },
      ],
      sources: [18],
      depth: 1,
      displayName: 'Some other race alone',
      percentLabel: '% of Some other race alone',
      numberFormatOptions: {},
      tags: [],
      context: [],
      childTags: [],
      resourcetype: 'CensusVariable',
    },
    {
      id: 195,
      name: 'Two or more races',
      slug: 'pop-by-race-two-or-more-races',
      description: '',
      shortName: null,
      units: null,
      unitNotes: null,
      denominators: [
        {
          id: 188,
          name: 'Total',
          slug: 'pop-by-race-total',
          depth: 0,
          percentLabel: '% of Total',
          shortName: null,
          numberFormatOptions: {},
          tags: [],
          context: [],
        },
      ],
      sources: [18],
      depth: 1,
      displayName: 'Two or more races',
      percentLabel: '% of Two or more races',
      numberFormatOptions: {},
      tags: [],
      context: [],
      childTags: [],
      resourcetype: 'CensusVariable',
    },
  ],
  sources: [
    {
      id: 18,
      name: '2019 ACS (5yr)',
      slug: '2019-acs-5yr',
      description:
        'The ACS is an ongoing survey that samples a small percentage of the population on questions regarding family and relationships, income, health insurance, education, employment, and disabilities.',
      infoLink: 'https://www.census.gov/programs-surveys/acs/',
      tags: [],
      context: [],
    },
  ],
  options: {
    note: null,
    useColumns: false,
    useDenominators: true,
    isSingleValue: false,
    isSingleton: { geog: false, time: true, vars: false },
    isMappable: false,
  },
  data: [
    [
      [
        { value: 2192.0, moe: 259.0, percent: null, denom: null },
        {
          value: 1794.0,
          moe: 239.0,
          percent: 0.8184306569343066,
          denom: 2192.0,
        },
        { value: 74.0, moe: 89.0, percent: 0.03375912408759124, denom: 2192.0 },
        {
          value: 232.0,
          moe: 123.0,
          percent: 0.10583941605839416,
          denom: 2192.0,
        },
        {
          value: 14.0,
          moe: 19.0,
          percent: 0.006386861313868613,
          denom: 2192.0,
        },
        {
          value: 0.0,
          moe: 10.0,
          percent: 0.0,
          denom: 2192.0,
        },
        {
          value: 10.0,
          moe: 17.0,
          percent: 0.004562043795620438,
          denom: 2192.0,
        },
        {
          value: 68.0,
          moe: 59.0,
          percent: 0.03102189781021898,
          denom: 2192.0,
        },
      ],
    ],
  ],
  dimensions: {
    geog: ['tract-42003070300'],
    time: ['most-recent-census-year-and-most-recent-acs-year:2019'],
    vars: [
      'pop-by-race-total',
      'pop-by-race-white-alone',
      'pop-by-race-black-or-african-american-alone',
      'pop-by-race-asian-alone',
      'pop-by-race-american-indian-and-alaska-native-alone',
      'pop-by-race-native-hawaiian-and-other-pacific-islander-alone',
      'pop-by-race-some-other-race-alone',
      'pop-by-race-two-or-more-races',
    ],
  },
  mapOptions: null,
  error: { status: 'OK', level: 0, message: '', record: null },
  warnings: [
    {
      status: 'WARNING',
      level: 10,
      message:
        'Margins of Error for compound variables cannot be accurately reported at this time.',
      record: null,
    },
    {
      status: 'WARNING',
      level: 10,
      message:
        "Cannot aggregate denominator data for '42003' at 'obesity-rates:2006' since data is not available for all of its constituent 'Tract's",
      record: null,
    },
  ],
  geogs: [
    {
      id: 2203,
      name: '703',
      slug: 'tract-42003070300',
      title: 'Tract 42003070300',
      geogType: 'tract',
      geogID: '42003070300',
      hierarchy: [
        {
          id: 1,
          name: 'Allegheny',
          slug: 'county-42003',
          title: 'Allegheny County',
          geogType: 'county',
          geogID: '42003',
        },
      ],
      overlap: {
        county: [{ name: 'Allegheny', slug: 'county-42003', id: 1 }],
        countySubdivision: [
          {
            name: 'Pittsburgh',
            slug: 'county-subdivision-4200361000',
            id: 3048,
          },
        ],
        neighborhood: [
          { name: 'Shadyside', slug: 'neighborhood-pgh-hood-68', id: 4093 },
        ],
        tract: [{ name: '703', slug: 'tract-42003070300', id: 2203 }],
      },
      centroid: [-79.93520938987699, 40.45078352039694],
      resourcetype: 'Tract',
    },
  ],
};
